// LOCALHOST 
###
//See API Docs
GET http://localhost:8080/api-docs HTTP/1.1

###
//Get all chores in the database
GET http://localhost:8080/chores HTTP/1.1

###
//Get a chore by id
GET http://localhost:8080/chores/64667bddf328a14c170fd987 HTTP/1.1

###
//Add a chore
POST http://localhost:8080/chores/add HTTP/1.1
content-type: application/json

{
  "choreName": "Testing Validation",
  "estimatedTime":"35 minutes",
  "indoor":"string",
  "outdoor":true,
  "spring":true,
  "summer":true,
  "fall":true,
  "winter":true
}

###
//Edit a chore
PUT http://localhost:8080/chores/edit/6463ee7d9c95f9aae921205e HTTP/1.1
content-type: application/json

{
  "choreName":"fold the laundry",
  "estimatedTime":"20 minutes",
  "indoor":true,
  "outdoor":false,
  "spring":true,
  "summer":true,
  "fall":true,
  "winter":true
}

###
//Delete a chore
DELETE http://localhost:8080/chores/delete/6470f6e6a982e946348981b3 HTTP/1.1

###
//Get all chore assignments in the database
GET http://localhost:8080/choreAssignments HTTP/1.1

###
//Get one child's chore assignment by id
GET http://localhost:8080/choreAssignments/647a26000fb73088f7991e9a HTTP/1.1

###
//Edit a chore assignment
PUT http://localhost:8080/choreAssignments/edit/647a26000fb73088f7991e9a HTTP/1.1
content-type: application/json

{
  "name":"Silas",
  "monday":"rake leaves",
  "tuesday":"clean the kitchen",
  "wednesday":"clean the bathrooms",
  "thursday":"clean the living room",
  "friday":"pull weeds"
}

###
//Delete a chore assignment
DELETE http://localhost:8080/choreAssignments/delete/647a27020fb73088f7991e9d HTTP/1.1


#--PRODUCTION DEPLOY---#
###
//See API Docs
GET https://cse341-project2-zuaa.onrender.com/api-docs

###
//Get all chores
GET https://cse341-project2-zuaa.onrender.com/chores 

###
//Get a chore by id
GET https://cse341-project2-zuaa.onrender.com/chores/6463ee7d9c95f9aae921205e

###
//Add a chore
POST https://cse341-project2-zuaa.onrender.com/chores/add HTTP/1.1
Content-Type: application/json

{
  "choreName":"here's a new chore to test",
  "estimatedTime":"30 minutes",
  "indoor":false,
  "outdoor":true,
  "spring":false,
  "summer":false,
  "fall":false,
  "winter":true
}

###
//Edit a chore
PUT https://cse341-project2-zuaa.onrender.com/chores/edit/6463ee7d9c95f9aae921205e HTTP/1.1
Content-Type: application/json

{
  "choreName":"fold the laundry",
  "estimatedTime":"25 minutes",
  "indoor":"true",
  "outdoor":"false",
  "spring":"true",
  "summer":"true",
  "fall":"true",
  "winter":"true"
}

###
//Delete a chore
DELETE https://cse341-project2-zuaa.onrender.com/chores/delete/6463f2359c95f9aae9212068 HTTP/1.1


